- name: Remove old Docker
  yum: name={{ item }} state=absent
  with_items:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

- name: add repo 
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 

- name: Centos Docker CE
  yum: name={{ item }} state=latest
  with_items:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  when: ansible_distribution == "Centos"

- name: Start docker service
  shell: systemctl daemon-reload && systemctl enable docker && systemctl restart docker

- name: adding existing user "{{ ansible_user }}" to group sudo
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 
    gpgcheck: no
    sslverify: no
    enabled: true
