- name: Install epel for Centos server
  yum: name={{ item }} state=latest
  with_items:
  - epel-release
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

- name: Install packages for Centos server
  yum: name={{ item }} state=latest
  with_items:
  - socat
  - ansible
  - htop 
  - git 
  - nload





